---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - myapp.demo.kubebuilder.io
  resources:
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - myapp.demo.kubebuilder.io
  resources:
  - redis/finalizers
  verbs:
  - update
- apiGroups:
  - myapp.demo.kubebuilder.io
  resources:
  - redis/status
  verbs:
  - get
  - patch
  - update
